export interface Order {
    identifier: string
    station_name: string
    order_number: string
    customer_name: string
    product_name: string
    product_part: string
    product_sku: string
    quantity: string
    delivery_date: string
    used_machine: string
    workloads: string
    estimate_start: string
    estimate_end: string
    actual_start: string
    actual_end: string
    duration: string
    assy_group: string
    part: string
    no_mode: string
    total_length: string
    stripping_front: string
    stripping_rear: string
    half_strip_front: string
    half_strip_end: string
    insulation_front: string
    insulation_back: string
    core_diameter: string
    blade_move_back: string
    depth_of_blade: string
    length_of_mb: string
    defect_item: string
    done_item: string
    completed: string
    status: string
}