export interface Order {
    identifier: string
    station_name: string
    order_number: string
    customer_name: string
    product_name: string
    product_code: string
    part_name: string
    part_code: string
    quantity: string
    delivery_date: string
    used_machine: string
    workloads: string
    estimate_start: string
    estimate_end: string
    actual_start: string
    actual_end: string
    duration: string
    total_length: string
    stripping_front: string
    stripping_rear: string
    defect_item: string
    done_item: string
    completed: string
    status: string
    created_by: string
    receiver: string
    shift: string
    checker: string
    qc: string
}